# Producion Agricola (Analisis Exploratorio de Datos)

Una vez realizados los ajustes pertinentes al conjunto de datos principal. Procedemos a realizar el analisis exploratorio de datos.
Donde conoceremos los datos y los iremos preparando para los futuroes modelos planteados.

**Observación** Una de las cosas distintivas con respecto a las etapas pasadas es que si nuestro problema lo requiere conectaremos nuestros datos principales con otras fuentes. Como veremos más adelante

In [50]:
from scripts.config import PRELOADS
import pickle

# Notemos que ahora estamos obteniendo la información ya normalizada.
with open(PRELOADS['AGROPROD_2'], "rb") as preprocess: 
    dgsiap = pickle.load(preprocess)

dgsiap

In [2]:
dataset = [file.open(pars=[1, {"low_memory":False, "index_col":0}]) for file in dgsiap.branch]

In [51]:
from scripts.config import DATA_DIR
import pandas as pd
import os

climate_path = DATA_DIR / "pure" / "OPENMETEO"
climate = [pd.read_csv(climate_path / f) for f in os.listdir(climate_path)]
test = climate[0]

In [52]:
michoacan = [df[df['Idestado'] == 16] for df in dataset]

for k, df in enumerate(michoacan):
    if k==0:
        df_micho = df
    df_micho = pd.concat([df_micho, df])


df_micho.reset_index(drop=True, inplace=True)

In [53]:
df_micho.head(n=5)

,Anio,Idestado,Nomestado,Idddr,Nomddr,Idcader,Nomcader,Idmunicipio,Nommunicipio,Idciclo,...,Nomunidad,Idcultivo,Nomcultivo,Sembrada,Cosechada,Siniestrada,Volumenproduccion,Rendimiento,Precio,Valorproduccion
0,2025,16,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,1,...,Tonelada,6840000,Frijol,133.0,133.0,0.0,118.30,0.89,21829.75,2582459.71
1,2025,16,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,1,...,Tonelada,7490000,Maíz grano,242.0,242.0,0.0,859.10,3.55,5572.05,4786948.16
2,2025,16,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,1,...,Tonelada,8790000,Sorgo forrajero en verde,50.0,50.0,0.0,1530.00,30.60,819.22,1253406.60
3,2025,16,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,1,...,Tonelada,8810000,Sorgo grano,37.0,37.0,0.0,121.36,3.28,4000.85,485543.16
4,2025,16,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,1,...,Tonelada,8970000,Tomate rojo (jitomate),9.6,9.6,0.0,292.80,30.50,9429.27,2760890.26

In [54]:
crops = df_micho['Nomcultivo'].unique().tolist()
len(crops)

166

In [55]:
crops_0 = crops[0]
crops_0

'Frijol'

In [56]:
micho_bean = df_micho[df_micho['Nomcultivo']==crops_0]

In [57]:
micho_bean

,Anio,Idestado,Nomestado,Idddr,Nomddr,Idcader,Nomcader,Idmunicipio,Nommunicipio,Idciclo,...,Nomunidad,Idcultivo,Nomcultivo,Sembrada,Cosechada,Siniestrada,Volumenproduccion,Rendimiento,Precio,Valorproduccion
0,2025,16,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,1,...,Tonelada,6840000,Frijol,133.0,133.0,0.0,118.30,0.89,21829.75,2582459.71
8,2025,16,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,2,...,Tonelada,6840000,Frijol,86.0,86.0,0.0,91.59,1.07,12335.50,1129808.45
26,2025,16,Michoacán,81,Coahuayana,2,Coahuayana,14,Coahuayana,1,...,Tonelada,6840000,Frijol,11.0,11.0,0.0,11.00,1.00,21323.05,234553.55
49,2025,16,Michoacán,81,Coahuayana,3,Chinicuila,26,Chinicuila,1,...,Tonelada,6840000,Frijol,11.0,10.5,0.5,10.20,0.97,20953.42,213724.88
61,2025,16,Michoacán,82,Aguililla,1,Aguililla,2,Aguililla,1,...,Tonelada,6840000,Frijol,16.0,14.0,2.0,16.52,1.18,20914.00,345499.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56884,2003,16,Michoacán,93,Zitácuaro,3,Ciudad Hidalgo,98,Tuxpan,2,...,Tonelada,6840000,Frijol,200.0,200.0,0.0,160.00,0.80,4500.00,720000.00
56945,2003,16,Michoacán,93,Zitácuaro,4,Zitácuaro,81,Susupuato,1,...,Tonelada,6840000,Frijol,2.0,2.0,0.0,2.00,1.00,5000.00,10000.00
56949,2003,16,Michoacán,93,Zitácuaro,4,Zitácuaro,81,Susupuato,2,...,Tonelada,6840000,Frijol,2.0,2.0,0.0,2.00,1.00,5000.00,10000.00
56961,2003,16,Michoacán,93,Zitácuaro,4,Zitácuaro,112,Zitácuaro,1,...,Tonelada,6840000,Frijol,2.0,2.0,0.0,2.00,1.00,5000.00,10000.00
56976,2003,16,Michoacán,93,Zitácuaro,4,Zitácuaro,112,Zitácuaro,2,...,Tonelada,6840000,Frijol,8.0,8.0,0.0,6.40,0.80,5000.00,32000.00

In [58]:
micho_muns = micho_bean['Nommunicipio'].unique().tolist()
len(micho_muns)

98

In [60]:
muns_0 = micho_muns[0]

micho_bmun = micho_bean[micho_bean['Nommunicipio']==muns_0]
print(micho_bmun.columns)
micho_bmun.drop(columns=['Idestado','Idcultivo','Idunidadmedida','Idmodalidad'], inplace=True)
micho_bmun

Index(['Anio', 'Idestado', 'Nomestado', 'Idddr', 'Nomddr', 'Idcader',
       'Nomcader', 'Idmunicipio', 'Nommunicipio', 'Idciclo',
       'Nomcicloproductivo', 'Idmodalidad', 'Nommodalidad', 'Idunidadmedida',
       'Nomunidad', 'Idcultivo', 'Nomcultivo', 'Sembrada', 'Cosechada',
       'Siniestrada', 'Volumenproduccion', 'Rendimiento', 'Precio',
       'Valorproduccion'],
      dtype='str')

,Anio,Nomestado,Idddr,Nomddr,Idcader,Nomcader,Idmunicipio,Nommunicipio,Idciclo,Nomcicloproductivo,Nommodalidad,Nomunidad,Nomcultivo,Sembrada,Cosechada,Siniestrada,Volumenproduccion,Rendimiento,Precio,Valorproduccion
0,2025,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,1,Otoño-Invierno,Riego,Tonelada,Frijol,133.0,133.0,0.0,118.30,0.89,21829.75,2582459.71
8,2025,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,2,Primavera-Verano,Temporal,Tonelada,Frijol,86.0,86.0,0.0,91.59,1.07,12335.50,1129808.45
2118,2025,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,1,Otoño-Invierno,Riego,Tonelada,Frijol,133.0,133.0,0.0,118.30,0.89,21829.75,2582459.71
2126,2025,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,2,Primavera-Verano,Temporal,Tonelada,Frijol,86.0,86.0,0.0,91.59,1.07,12335.50,1129808.45
4236,2024,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,1,Otoño-Invierno,Riego,Tonelada,Frijol,137.0,137.0,0.0,125.94,0.92,11480.14,1445808.96
4244,2024,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,2,Primavera-Verano,Temporal,Tonelada,Frijol,90.0,90.0,0.0,94.50,1.05,12395.56,1171380.42
6525,2023,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,1,Otoño-Invierno,Riego,Tonelada,Frijol,100.0,100.0,0.0,89.80,0.90,13409.59,1204180.83
6533,2023,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,2,Primavera-Verano,Temporal,Tonelada,Frijol,88.0,88.0,0.0,95.04,1.08,13100.00,1245024.00
8877,2022,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,1,Otoño-Invierno,Riego,Tonelada,Frijol,117.0,117.0,0.0,109.26,0.93,13398.13,1463880.00
8885,2022,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,2,Primavera-Verano,Temporal,Tonelada,Frijol,86.0,86.0,0.0,91.16,1.06,12100.00,1103036.00
11143,2021,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,1,Otoño-Invierno,Riego,Tonelada,Frijol,135.0,135.0,0.0,136.35,1.01,11628.13,1585495.53
11150,2021,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,2,Primavera-Verano,Temporal,Tonelada,Frijol,86.0,86.0,0.0,91.16,1.06,15100.00,1376516.00
12927,2020,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,1,Otoño-Invierno,Riego,Tonelada,Frijol,106.0,106.0,0.0,98.58,0.93,14749.66,1454021.48
12934,2020,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,2,Primavera-Verano,Temporal,Tonelada,Frijol,85.0,85.0,0.0,90.10,1.06,15000.00,1351500.00
14640,2019,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,1,Otoño-Invierno,Riego,Tonelada,Frijol,87.0,87.0,0.0,79.17,0.91,12245.46,969472.89
14648,2019,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,2,Primavera-Verano,Temporal,Tonelada,Frijol,47.0,47.0,0.0,37.60,0.80,15200.00,571520.00
16963,2018,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,1,Otoño-Invierno,Riego,Tonelada,Frijol,100.0,100.0,0.0,126.20,1.26,11794.13,1488419.47
16971,2018,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,2,Primavera-Verano,Temporal,Tonelada,Frijol,84.0,84.0,0.0,99.96,1.19,13437.25,1343187.51
19379,2017,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,1,Otoño-Invierno,Riego,Tonelada,Frijol,98.0,98.0,0.0,117.60,1.20,10200.85,1199619.96
19387,2017,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,2,Primavera-Verano,Temporal,Tonelada,Frijol,124.0,124.0,0.0,146.32,1.18,12619.60,1846499.87
21941,2016,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,1,Otoño-Invierno,Riego,Tonelada,Frijol,92.0,92.0,0.0,101.20,1.10,10025.30,1014560.36
21949,2016,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,2,Primavera-Verano,Temporal,Tonelada,Frijol,112.0,112.0,0.0,123.20,1.10,12789.57,1575675.02
24490,2015,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,1,Otoño-Invierno,Riego,Tonelada,Frijol,90.0,90.0,0.0,72.00,0.80,9000.00,648000.00
24498,2015,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,2,Primavera-Verano,Temporal,Tonelada,Frijol,110.0,110.0,0.0,101.20,0.92,10139.09,1026075.91
27035,2014,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,1,Otoño-Invierno,Riego,Tonelada,Frijol,80.0,80.0,0.0,80.00,1.00,12300.00,984000.00
27043,2014,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,2,Primavera-Verano,Temporal,Tonelada,Frijol,201.0,201.0,0.0,201.00,1.00,10000.00,2010000.00
29385,2013,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,1,Otoño-Invierno,Riego,Tonelada,Frijol,108.7,108.7,0.0,107.50,0.99,12714.42,1366800.15
29393,2013,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,2,Primavera-Verano,Temporal,Tonelada,Frijol,210.0,202.0,8.0,157.60,0.78,8619.28,1358398.53
31769,2012,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,1,Otoño-Invierno,Riego,Tonelada,Frijol,130.0,130.0,0.0,133.90,1.03,10471.26,1402101.71
31776,2012,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,2,Primavera-Verano,Temporal,Tonelada,Frijol,40.0,40.0,0.0,41.20,1.03,12029.13,495600.16
34206,2011,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,1,Otoño-Invierno,Riego,Tonelada,Frijol,85.0,85.0,0.0,86.40,1.02,8208.33,709199.71
34213,2011,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,2,Primavera-Verano,Temporal,Tonelada,Frijol,40.0,40.0,0.0,42.20,1.06,9707.35,409650.17
36649,2010,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,1,Otoño-Invierno,Riego,Tonelada,Frijol,85.0,85.0,0.0,84.80,1.00,8200.00,695360.00
36656,2010,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,2,Primavera-Verano,Temporal,Tonelada,Frijol,40.0,40.0,0.0,40.60,1.02,9000.00,365400.00
39187,2009,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,1,Otoño-Invierno,Riego,Tonelada,Frijol,150.0,150.0,0.0,152.70,1.02,8000.00,1221600.00
39194,2009,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,2,Primavera-Verano,Temporal,Tonelada,Frijol,40.0,40.0,0.0,44.00,1.10,8500.00,374000.00
41675,2008,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,1,Otoño-Invierno,Riego,Tonelada,Frijol,125.0,125.0,0.0,128.60,1.03,9000.00,1157400.00
41682,2008,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,2,Primavera-Verano,Temporal,Tonelada,Frijol,30.0,30.0,0.0,30.00,1.00,9000.00,270000.00
44232,2007,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,1,Otoño-Invierno,Riego,Tonelada,Frijol,160.0,160.0,0.0,169.40,1.06,8000.00,1355200.00
44239,2007,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,2,Primavera-Verano,Temporal,Tonelada,Frijol,35.0,35.0,0.0,37.70,1.08,8000.00,301600.00
46785,2006,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,1,Otoño-Invierno,Riego,Tonelada,Frijol,40.0,40.0,0.0,40.80,1.02,7000.00,285600.00
46791,2006,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,2,Primavera-Verano,Temporal,Tonelada,Frijol,46.0,46.0,0.0,48.90,1.06,8000.00,391200.00
49288,2005,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,1,Otoño-Invierno,Riego,Tonelada,Frijol,40.0,40.0,0.0,40.40,1.01,7000.00,282800.00
49294,2005,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,2,Primavera-Verano,Temporal,Tonelada,Frijol,5.0,5.0,0.0,5.00,1.00,6500.00,32500.00
51825,2004,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,1,Otoño-Invierno,Riego,Tonelada,Frijol,40.0,40.0,0.0,41.80,1.05,6500.00,271700.00
54437,2003,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,1,Otoño-Invierno,Riego,Tonelada,Frijol,35.0,35.0,0.0,42.00,1.20,4000.00,168000.00

In [61]:
df = micho_bmun.groupby('Anio')[['Sembrada','Cosechada','Siniestrada']].sum()
df['TasaExito'] = df['Cosechada'] / df['Sembrada']
df

      Sembrada  Cosechada  Siniestrada  TasaExito
Anio
2003      35.0       35.0          0.0   1.000000
2004      40.0       40.0          0.0   1.000000
2005      45.0       45.0          0.0   1.000000
2006      86.0       86.0          0.0   1.000000
2007     195.0      195.0          0.0   1.000000
2008     155.0      155.0          0.0   1.000000
2009     190.0      190.0          0.0   1.000000
2010     125.0      125.0          0.0   1.000000
2011     125.0      125.0          0.0   1.000000
2012     170.0      170.0          0.0   1.000000
2013     318.7      310.7          8.0   0.974898
2014     281.0      281.0          0.0   1.000000
2015     200.0      200.0          0.0   1.000000
2016     204.0      204.0          0.0   1.000000
2017     222.0      222.0          0.0   1.000000
2018     184.0      184.0          0.0   1.000000
2019     134.0      134.0          0.0   1.000000
2020     191.0      191.0          0.0   1.000000
2021     221.0      221.0          0.0   1.000000
2022     203.0      203.0          0.0   1.000000
2023     188.0      188.0          0.0   1.000000
2024     227.0      227.0          0.0   1.000000
2025     438.0      438.0          0.0   1.000000

In [62]:
micho_clima = climate[0]
reg_clima = micho_clima[micho_clima['Nommunicipio']==muns_0]
reg_clima.set_index('Anio',drop=True, inplace=True)
reg_clima

,Temperatura_media,Temperatura_maxima,Temperatura_minima,Precipitacion_anual,Dias_con_lluvia,Horas_precipitacion,Evapotranspiracion_anual,Idestado,Idmunicipio,Nommunicipio,Latitud,Longitud
Anio,,,,,,,,,,,,
2003,23.00,34.4,9.6,1996.5,196,1635.0,1504.18,16,8,Aquila,18.383407,-103.316649
2004,22.89,34.9,8.9,1835.6,221,1628.0,1490.37,16,8,Aquila,18.383407,-103.316649
2005,22.91,33.2,10.0,1986.4,188,1539.0,1507.58,16,8,Aquila,18.383407,-103.316649
2006,23.01,32.6,10.9,2186.3,215,1805.0,1469.68,16,8,Aquila,18.383407,-103.316649
2007,23.11,32.7,12.2,2130.6,213,1615.0,1501.43,16,8,Aquila,18.383407,-103.316649
2008,22.51,33.2,8.1,1935.2,193,1619.0,1508.73,16,8,Aquila,18.383407,-103.316649
2009,22.94,32.1,10.6,1575.3,211,1468.0,1518.75,16,8,Aquila,18.383407,-103.316649
2010,22.41,34.0,10.3,2353.6,188,1813.0,1444.52,16,8,Aquila,18.383407,-103.316649
2011,22.87,32.5,8.4,2404.8,206,1848.0,1467.46,16,8,Aquila,18.383407,-103.316649
2012,22.89,32.7,11.6,2023.7,234,1798.0,1447.69,16,8,Aquila,18.383407,-103.316649
2013,23.01,32.0,13.5,2074.5,232,1779.0,1464.58,16,8,Aquila,18.383407,-103.316649
2014,23.02,32.3,12.8,2279.8,248,1951.0,1421.69,16,8,Aquila,18.383407,-103.316649
2015,23.62,33.4,11.0,2098.4,245,1770.0,1460.78,16,8,Aquila,18.383407,-103.316649
2016,23.28,32.9,8.0,1916.1,230,1554.0,1501.95,16,8,Aquila,18.383407,-103.316649
2017,23.07,33.0,11.2,1998.9,215,1716.0,1479.67,16,8,Aquila,18.383407,-103.316649
2018,23.07,33.1,11.0,1855.5,221,1682.0,1468.81,16,8,Aquila,18.383407,-103.316649
2019,23.22,33.5,10.3,2016.6,212,1637.0,1504.15,16,8,Aquila,18.383407,-103.316649
2020,23.41,33.8,10.4,1744.0,201,1460.0,1543.21,16,8,Aquila,18.383407,-103.316649
2021,22.88,32.6,8.7,2268.4,200,1747.0,1508.87,16,8,Aquila,18.383407,-103.316649
2022,22.83,33.6,11.2,1875.9,232,1943.0,1488.16,16,8,Aquila,18.383407,-103.316649
2023,23.49,33.4,10.9,1740.7,224,1830.0,1531.54,16,8,Aquila,18.383407,-103.316649
2024,23.65,33.9,10.4,1839.3,199,1766.0,1541.57,16,8,Aquila,18.383407,-103.316649
2025,23.56,35.2,12.5,2114.0,248,2003.0,1496.24,16,8,Aquila,18.383407,-103.316649

In [132]:
model = reg_clima.drop(columns=["Idestado", "Idmunicipio", "Nommunicipio","Latitud", "Longitud"])
model['TasaExito']=df['TasaExito']
model

,Temperatura_media,Temperatura_maxima,Temperatura_minima,Precipitacion_anual,Dias_con_lluvia,Horas_precipitacion,Evapotranspiracion_anual,TasaExito
Anio,,,,,,,,
2003,23.00,34.4,9.6,1996.5,196,1635.0,1504.18,1.000000
2004,22.89,34.9,8.9,1835.6,221,1628.0,1490.37,1.000000
2005,22.91,33.2,10.0,1986.4,188,1539.0,1507.58,1.000000
2006,23.01,32.6,10.9,2186.3,215,1805.0,1469.68,1.000000
2007,23.11,32.7,12.2,2130.6,213,1615.0,1501.43,1.000000
2008,22.51,33.2,8.1,1935.2,193,1619.0,1508.73,1.000000
2009,22.94,32.1,10.6,1575.3,211,1468.0,1518.75,1.000000
2010,22.41,34.0,10.3,2353.6,188,1813.0,1444.52,1.000000
2011,22.87,32.5,8.4,2404.8,206,1848.0,1467.46,1.000000
2012,22.89,32.7,11.6,2023.7,234,1798.0,1447.69,1.000000
2013,23.01,32.0,13.5,2074.5,232,1779.0,1464.58,0.974898
2014,23.02,32.3,12.8,2279.8,248,1951.0,1421.69,1.000000
2015,23.62,33.4,11.0,2098.4,245,1770.0,1460.78,1.000000
2016,23.28,32.9,8.0,1916.1,230,1554.0,1501.95,1.000000
2017,23.07,33.0,11.2,1998.9,215,1716.0,1479.67,1.000000
2018,23.07,33.1,11.0,1855.5,221,1682.0,1468.81,1.000000
2019,23.22,33.5,10.3,2016.6,212,1637.0,1504.15,1.000000
2020,23.41,33.8,10.4,1744.0,201,1460.0,1543.21,1.000000
2021,22.88,32.6,8.7,2268.4,200,1747.0,1508.87,1.000000
2022,22.83,33.6,11.2,1875.9,232,1943.0,1488.16,1.000000
2023,23.49,33.4,10.9,1740.7,224,1830.0,1531.54,1.000000
2024,23.65,33.9,10.4,1839.3,199,1766.0,1541.57,1.000000
2025,23.56,35.2,12.5,2114.0,248,2003.0,1496.24,1.000000

In [134]:
import matplotlib.pyplot as plt

traindata = model[model["TasaExito"] ==1]
prob = model[model["TasaExito"] <1]
traindata

,Temperatura_media,Temperatura_maxima,Temperatura_minima,Precipitacion_anual,Dias_con_lluvia,Horas_precipitacion,Evapotranspiracion_anual,TasaExito
Anio,,,,,,,,
2003,23.00,34.4,9.6,1996.5,196,1635.0,1504.18,1.0
2004,22.89,34.9,8.9,1835.6,221,1628.0,1490.37,1.0
2005,22.91,33.2,10.0,1986.4,188,1539.0,1507.58,1.0
2006,23.01,32.6,10.9,2186.3,215,1805.0,1469.68,1.0
2007,23.11,32.7,12.2,2130.6,213,1615.0,1501.43,1.0
2008,22.51,33.2,8.1,1935.2,193,1619.0,1508.73,1.0
2009,22.94,32.1,10.6,1575.3,211,1468.0,1518.75,1.0
2010,22.41,34.0,10.3,2353.6,188,1813.0,1444.52,1.0
2011,22.87,32.5,8.4,2404.8,206,1848.0,1467.46,1.0
2012,22.89,32.7,11.6,2023.7,234,1798.0,1447.69,1.0
2014,23.02,32.3,12.8,2279.8,248,1951.0,1421.69,1.0
2015,23.62,33.4,11.0,2098.4,245,1770.0,1460.78,1.0
2016,23.28,32.9,8.0,1916.1,230,1554.0,1501.95,1.0
2017,23.07,33.0,11.2,1998.9,215,1716.0,1479.67,1.0
2018,23.07,33.1,11.0,1855.5,221,1682.0,1468.81,1.0
2019,23.22,33.5,10.3,2016.6,212,1637.0,1504.15,1.0
2020,23.41,33.8,10.4,1744.0,201,1460.0,1543.21,1.0
2021,22.88,32.6,8.7,2268.4,200,1747.0,1508.87,1.0
2022,22.83,33.6,11.2,1875.9,232,1943.0,1488.16,1.0
2023,23.49,33.4,10.9,1740.7,224,1830.0,1531.54,1.0
2024,23.65,33.9,10.4,1839.3,199,1766.0,1541.57,1.0
2025,23.56,35.2,12.5,2114.0,248,2003.0,1496.24,1.0

In [135]:
prob

,Temperatura_media,Temperatura_maxima,Temperatura_minima,Precipitacion_anual,Dias_con_lluvia,Horas_precipitacion,Evapotranspiracion_anual,TasaExito
Anio,,,,,,,,
2013,23.01,32.0,13.5,2074.5,232,1779.0,1464.58,0.974898

In [136]:
import torch
import numpy as np
from torch import nn
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

batch_size = 5
shuffle = True

features = traindata.iloc[:,:-1]
X = features.to_numpy()
target = features.iloc[:, -1].to_numpy()

dataset = TensorDataset(torch.Tensor(X), torch.Tensor(target))

dataloader=DataLoader(dataset, batch_size=batch_size, shuffle=1)

m = nn.Linear(in_features=7,out_features=10)
x = torch.rand(1, 7)
x1 = nn.Sigmoid()(m(x))
m1 = nn.Linear(in_features=10, out_features=1)
y = m1(x1)

crit = nn.MSELoss()

loss = crit(y.double(), torch.tensor([1]).double())
loss.backward()

optimizer = torch.optim.SGD(m.parameters(), lr=0.001)

optimizer.step()

y

/home/david/Documents/Repositories/academica/proyecto_agronomia/.venv/lib/python3.14/site-packages/torch/nn/modules/loss.py:630: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)

tensor([[0.0711]], grad_fn=<AddmmBackward0>)

In [165]:
import torch
import numpy as np
from torch import nn
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

batch_size = 5
shuffle = True

features = traindata.iloc[:,:-1]
X = features.to_numpy()
target = traindata.iloc[:, -1].to_numpy()

dataset = TensorDataset(torch.Tensor(X), torch.Tensor(target))

dataloader=DataLoader(dataset, batch_size=batch_size, shuffle=1)

agromodel = nn.Sequential(nn.Linear(in_features=7,out_features=10),
nn.Linear(in_features=10, out_features=1))


crit = nn.MSELoss()
optimizer = torch.optim.SGD(agromodel.parameters(), lr=0.001)

for epoch in range(1_000):
    for data in dataloader:
        optimizer.zero_grad()
        feature, target = data
        pred = agromodel(feature)
        loss = crit(pred, target)
        loss.backward()
        optimizer.step()

/home/david/Documents/Repositories/academica/proyecto_agronomia/.venv/lib/python3.14/site-packages/torch/nn/modules/loss.py:630: UserWarning: Using a target size (torch.Size([5])) that is different to the input size (torch.Size([5, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
/home/david/Documents/Repositories/academica/proyecto_agronomia/.venv/lib/python3.14/site-packages/torch/nn/modules/loss.py:630: UserWarning: Using a target size (torch.Size([2])) that is different to the input size (torch.Size([2, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)

In [164]:
test = prob.iloc[:,:-1].to_numpy()
test

array([[  23.01,   32.  ,   13.5 , 2074.5 ,  232.  , 1779.  , 1464.58]])

In [161]:
uq = torch.Tensor(traindata.loc[2003].iloc[:-1].to_numpy())

In [162]:
agromodel(uq).detach().numpy()

array([nan], dtype=float32)