# Preparación de Datos.

En la parte anterior descargamos y preprocesamos los datos del DGSIAP. Ahora dejaremos de lado la gestion de los datos y nos centraremos en los datos mismos.

In [1]:
# Obtenemos los datos a procesar
from scripts.config import PRELOADS
import pickle

with open(PRELOADS['AGROPROD_0'], "rb") as preprocess: 
    dgsiap = pickle.load(preprocess)

# Verificamos que los archiovs se encuentren en el archivo precargado
dgsiap.root

## Carga desde raw.

Ahora vamos a cargar los archivos desde la carpeta /raw

In [2]:
datadic = dgsiap.root

codebook = datadic.open()
codebook.head()

,Unnamed: 0.1,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Viendo que el diccionario de datos no esta bien formateado. Vamos a experimentar con él.

### Diccionario de Datos

In [50]:
import pandas as pd
ubi = datadic.ubication
# Quitamos rengolnes y elegimos el nombre de las variables como 
exc = pd.read_excel(ubi, skiprows=9, index_col=2)


# Introducimos el siguiente conjunto de paramentos
exc_pars = {"skiprows":9,
            "index_col":2}

df = pd.read_excel(ubi, **exc_pars)
# print(df.columns)
v = list(df.columns)[:2]
df.drop(columns=list(df.columns)[:2])

# Todo esto será guardado en un formato personalizado.

def preconfig(df):
    # Esto puede cambiar en función de la base de datos.
    subdf = df.iloc[-7:-1,1:2]
    delete_columns = list(df.columns)[:2]
    new_df = df.drop(columns=delete_columns)
    new_df = df.iloc[-7:]
    return subdf, new_df

# Usando la clase File

codebook = datadic.open(pars=[1, exc_pars])
vars, codes = preconfig(codebook)
print(vars)
codes

                    Consecutivo\nen la base
Nombre\nde campo
NaN                                     NaN
NaN                                T: Texto
NaN                       N:Numérico entero
NaN                     D: Numérico decimal
NaN                   #: Carácter numérico.
NaN               A: Carácter alfanumérico.

,8,Consecutivo\nen la base,Tipo,Long.,Rangos\nválidos,Descripción,Observaciones
Nombre de campo,,,,,,,
NaN,33,NaN,NaN,NaN,NaN,NaN,NaN
NaN,34,T: Texto,NaN,NaN,NaN,NaN,NaN
NaN,35,N:Numérico entero,NaN,NaN,NaN,NaN,NaN
NaN,36,D: Numérico decimal,NaN,NaN,NaN,NaN,NaN
NaN,37,#: Carácter numérico.,NaN,NaN,NaN,NaN,NaN
NaN,38,A: Carácter alfanumérico.,NaN,NaN,NaN,NaN,NaN
NaN,39,Fuente: Dirección General del Servicio de Info...,NaN,NaN,NaN,NaN,NaN

Del diccionario de datos obtuvimos dos elementos

* El catalogo: Donde vemos la información de las variables
* Las variables: Los tipos de datos utilizados en los datos.

Vamos a formatear los datos para usarlos más adelante.

In [51]:
vars = vars['Consecutivo\nen la base'].to_list()[1:]
guide_vars = {v.split(":")[0]: v.split(":")[-1].strip() for v in vars}
guide_vars

{'T': 'Texto',
 'N': 'Numérico entero',
 'D': 'Numérico decimal',
 '#': 'Carácter numérico.',
 'A': 'Carácter alfanumérico.'}