# Producion Agricola (Analisis Exploratorio de Datos)

Una vez realizados los ajustes pertinentes al conjunto de datos principal. Procedemos a realizar el analisis exploratorio de datos.
Donde conoceremos los datos y los iremos preparando para los futuroes modelos planteados.

**Observación** Una de las cosas distintivas con respecto a las etapas pasadas es que si nuestro problema lo requiere conectaremos nuestros datos principales con otras fuentes. Como veremos más adelante

In [ ]:
from scripts.config import PRELOADS
import pickle

# Notemos que ahora estamos obteniendo la información ya normalizada.
with open(PRELOADS['AGROPROD_2'], "rb") as preprocess: 
    dgsiap = pickle.load(preprocess)

dgsiap

In [5]:
dataset = [file.open(pars=[1, {"low_memory":False, "index_col":0}]) for file in dgsiap.branch]

In [ ]:
from scripts.config import DATA_DIR
import pandas as pd
import os

climate_path = DATA_DIR / "pure" / "OPENMETEO"
climate = [pd.read_csv(climate_path / f) for f in os.listdir(climate_path)]
test = climate[0]

,Anio,Temperatura_media,Temperatura_maxima,Temperatura_minima,Precipitacion_anual,Dias_con_lluvia,Horas_precipitacion,Evapotranspiracion_anual,Idestado,Idmunicipio,Nommunicipio,Latitud,Longitud
0,2003,16.93,32.6,3.0,780.4,196,1146.0,1441.83,16,1,Acuitzio,19.471548,-101.325769
1,2004,16.47,29.1,2.4,800.9,208,1217.0,1403.83,16,1,Acuitzio,19.471548,-101.325769
2,2005,17.26,32.6,3.7,649.3,173,964.0,1482.93,16,1,Acuitzio,19.471548,-101.325769
3,2006,16.80,30.9,1.5,964.9,214,1245.0,1410.13,16,1,Acuitzio,19.471548,-101.325769
4,2007,16.79,30.0,4.7,925.3,202,1245.0,1437.03,16,1,Acuitzio,19.471548,-101.325769
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2594,2021,19.78,34.5,3.4,1014.9,149,1298.0,1662.86,16,113,José Sixto Verduzco,20.241913,-101.589964
2595,2022,20.17,36.2,6.3,666.4,154,1282.0,1725.20,16,113,José Sixto Verduzco,20.241913,-101.589964
2596,2023,20.63,37.3,4.9,599.3,161,1062.0,1753.22,16,113,José Sixto Verduzco,20.241913,-101.589964
2597,2024,21.11,38.7,4.6,918.6,131,1342.0,1768.61,16,113,José Sixto Verduzco,20.241913,-101.589964
2598,2025,20.46,37.0,5.8,936.8,163,1514.0,1697.04,16,113,José Sixto Verduzco,20.241913,-101.589964

In [17]:
michoacan = [df[df['Idestado'] == 16] for df in dataset]

for k, df in enumerate(michoacan):
    if k==0:
        df_micho = df
    df_micho = pd.concat([df_micho, df])


df_micho.reset_index(drop=True, inplace=True)

In [19]:
df_micho.head(n=5)

,Anio,Idestado,Nomestado,Idddr,Nomddr,Idcader,Nomcader,Idmunicipio,Nommunicipio,Idciclo,...,Nomunidad,Idcultivo,Nomcultivo,Sembrada,Cosechada,Siniestrada,Volumenproduccion,Rendimiento,Precio,Valorproduccion
0,2025,16,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,1,...,Tonelada,6840000,Frijol,133.0,133.0,0.0,118.30,0.89,21829.75,2582459.71
1,2025,16,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,1,...,Tonelada,7490000,Maíz grano,242.0,242.0,0.0,859.10,3.55,5572.05,4786948.16
2,2025,16,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,1,...,Tonelada,8790000,Sorgo forrajero en verde,50.0,50.0,0.0,1530.00,30.60,819.22,1253406.60
3,2025,16,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,1,...,Tonelada,8810000,Sorgo grano,37.0,37.0,0.0,121.36,3.28,4000.85,485543.16
4,2025,16,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,1,...,Tonelada,8970000,Tomate rojo (jitomate),9.6,9.6,0.0,292.80,30.50,9429.27,2760890.26

In [24]:
crops = df_micho['Nomcultivo'].unique().tolist()
len(crops)

166

In [25]:
crops_0 = crops[0]
crops_0

'Frijol'

In [26]:
micho_bean = df_micho[df_micho['Nomcultivo']==crops_0]

In [27]:
micho_bean

,Anio,Idestado,Nomestado,Idddr,Nomddr,Idcader,Nomcader,Idmunicipio,Nommunicipio,Idciclo,...,Nomunidad,Idcultivo,Nomcultivo,Sembrada,Cosechada,Siniestrada,Volumenproduccion,Rendimiento,Precio,Valorproduccion
0,2025,16,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,1,...,Tonelada,6840000,Frijol,133.0,133.0,0.0,118.30,0.89,21829.75,2582459.71
8,2025,16,Michoacán,81,Coahuayana,1,Aquila,8,Aquila,2,...,Tonelada,6840000,Frijol,86.0,86.0,0.0,91.59,1.07,12335.50,1129808.45
26,2025,16,Michoacán,81,Coahuayana,2,Coahuayana,14,Coahuayana,1,...,Tonelada,6840000,Frijol,11.0,11.0,0.0,11.00,1.00,21323.05,234553.55
49,2025,16,Michoacán,81,Coahuayana,3,Chinicuila,26,Chinicuila,1,...,Tonelada,6840000,Frijol,11.0,10.5,0.5,10.20,0.97,20953.42,213724.88
61,2025,16,Michoacán,82,Aguililla,1,Aguililla,2,Aguililla,1,...,Tonelada,6840000,Frijol,16.0,14.0,2.0,16.52,1.18,20914.00,345499.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56884,2003,16,Michoacán,93,Zitácuaro,3,Ciudad Hidalgo,98,Tuxpan,2,...,Tonelada,6840000,Frijol,200.0,200.0,0.0,160.00,0.80,4500.00,720000.00
56945,2003,16,Michoacán,93,Zitácuaro,4,Zitácuaro,81,Susupuato,1,...,Tonelada,6840000,Frijol,2.0,2.0,0.0,2.00,1.00,5000.00,10000.00
56949,2003,16,Michoacán,93,Zitácuaro,4,Zitácuaro,81,Susupuato,2,...,Tonelada,6840000,Frijol,2.0,2.0,0.0,2.00,1.00,5000.00,10000.00
56961,2003,16,Michoacán,93,Zitácuaro,4,Zitácuaro,112,Zitácuaro,1,...,Tonelada,6840000,Frijol,2.0,2.0,0.0,2.00,1.00,5000.00,10000.00
56976,2003,16,Michoacán,93,Zitácuaro,4,Zitácuaro,112,Zitácuaro,2,...,Tonelada,6840000,Frijol,8.0,8.0,0.0,6.40,0.80,5000.00,32000.00

In [29]:
micho_muns = micho_bean['Nommunicipio'].unique().tolist()
len(micho_muns)

98

In [94]:
muns_0 = micho_muns[3]

micho_bmun = micho_bean[micho_bean['Nommunicipio']==muns_0]
print(micho_bmun.columns)
micho_bmun.drop(columns=['Idestado','Idcultivo','Idunidadmedida','Idmodalidad'], inplace=True)
micho_bmun

Index(['Anio', 'Idestado', 'Nomestado', 'Idddr', 'Nomddr', 'Idcader',
       'Nomcader', 'Idmunicipio', 'Nommunicipio', 'Idciclo',
       'Nomcicloproductivo', 'Idmodalidad', 'Nommodalidad', 'Idunidadmedida',
       'Nomunidad', 'Idcultivo', 'Nomcultivo', 'Sembrada', 'Cosechada',
       'Siniestrada', 'Volumenproduccion', 'Rendimiento', 'Precio',
       'Valorproduccion'],
      dtype='str')

,Anio,Nomestado,Idddr,Nomddr,Idcader,Nomcader,Idmunicipio,Nommunicipio,Idciclo,Nomcicloproductivo,Nommodalidad,Nomunidad,Nomcultivo,Sembrada,Cosechada,Siniestrada,Volumenproduccion,Rendimiento,Precio,Valorproduccion
61,2025,Michoacán,82,Aguililla,1,Aguililla,2,Aguililla,1,Otoño-Invierno,Riego,Tonelada,Frijol,16.0,14.0,2.0,16.52,1.18,20914.00,345499.28
2179,2025,Michoacán,82,Aguililla,1,Aguililla,2,Aguililla,1,Otoño-Invierno,Riego,Tonelada,Frijol,16.0,14.0,2.0,16.52,1.18,20914.00,345499.28
4307,2024,Michoacán,82,Aguililla,1,Aguililla,2,Aguililla,1,Otoño-Invierno,Riego,Tonelada,Frijol,17.0,17.0,0.0,25.50,1.50,12905.88,329099.94
4318,2024,Michoacán,82,Aguililla,1,Aguililla,2,Aguililla,2,Primavera-Verano,Temporal,Tonelada,Frijol,6.0,6.0,0.0,5.04,0.84,13220.00,66628.80
6597,2023,Michoacán,82,Aguililla,1,Aguililla,2,Aguililla,1,Otoño-Invierno,Riego,Tonelada,Frijol,17.0,17.0,0.0,25.50,1.50,13700.00,349350.00
6608,2023,Michoacán,82,Aguililla,1,Aguililla,2,Aguililla,2,Primavera-Verano,Temporal,Tonelada,Frijol,6.4,5.4,1.0,4.59,0.85,13650.00,62653.50
8946,2022,Michoacán,82,Aguililla,1,Aguililla,2,Aguililla,1,Otoño-Invierno,Riego,Tonelada,Frijol,16.0,16.0,0.0,14.88,0.93,13500.00,200880.00
11200,2021,Michoacán,82,Aguililla,1,Aguililla,2,Aguililla,1,Otoño-Invierno,Riego,Tonelada,Frijol,16.0,16.0,0.0,14.40,0.90,12900.00,185760.00
11210,2021,Michoacán,82,Aguililla,1,Aguililla,2,Aguililla,2,Primavera-Verano,Temporal,Tonelada,Frijol,5.0,5.0,0.0,2.50,0.50,13500.00,33750.00
12984,2020,Michoacán,82,Aguililla,1,Aguililla,2,Aguililla,1,Otoño-Invierno,Riego,Tonelada,Frijol,3.0,3.0,0.0,3.60,1.20,13200.00,47520.00
12993,2020,Michoacán,82,Aguililla,1,Aguililla,2,Aguililla,2,Primavera-Verano,Temporal,Tonelada,Frijol,5.0,5.0,0.0,2.50,0.50,13200.00,33000.00
14712,2019,Michoacán,82,Aguililla,1,Aguililla,2,Aguililla,1,Otoño-Invierno,Riego,Tonelada,Frijol,12.0,12.0,0.0,14.20,1.18,12200.00,173240.00
14724,2019,Michoacán,82,Aguililla,1,Aguililla,2,Aguililla,2,Primavera-Verano,Temporal,Tonelada,Frijol,4.0,4.0,0.0,1.20,0.30,12500.00,15000.00
19453,2017,Michoacán,82,Aguililla,1,Aguililla,2,Aguililla,1,Otoño-Invierno,Riego,Tonelada,Frijol,3.0,3.0,0.0,1.80,0.60,11000.00,19800.00
22014,2016,Michoacán,82,Aguililla,1,Aguililla,2,Aguililla,1,Otoño-Invierno,Riego,Tonelada,Frijol,11.0,11.0,0.0,4.84,0.44,11627.27,56275.99
24556,2015,Michoacán,82,Aguililla,1,Aguililla,2,Aguililla,1,Otoño-Invierno,Riego,Tonelada,Frijol,7.5,7.5,0.0,3.53,0.47,8000.00,28240.00
24565,2015,Michoacán,82,Aguililla,1,Aguililla,2,Aguililla,2,Primavera-Verano,Temporal,Tonelada,Frijol,4.5,4.5,0.0,1.71,0.38,9000.00,15390.00
27102,2014,Michoacán,82,Aguililla,1,Aguililla,2,Aguililla,1,Otoño-Invierno,Riego,Tonelada,Frijol,10.0,10.0,0.0,4.20,0.42,13000.00,54600.00
27107,2014,Michoacán,82,Aguililla,1,Aguililla,2,Aguililla,1,Otoño-Invierno,Temporal,Tonelada,Frijol,2.0,0.0,2.0,0.00,0.00,0.00,0.00
27113,2014,Michoacán,82,Aguililla,1,Aguililla,2,Aguililla,2,Primavera-Verano,Temporal,Tonelada,Frijol,6.0,6.0,0.0,2.70,0.45,10617.78,28668.01
29450,2013,Michoacán,82,Aguililla,1,Aguililla,2,Aguililla,1,Otoño-Invierno,Riego,Tonelada,Frijol,4.0,4.0,0.0,1.80,0.45,4906.00,8830.80
29460,2013,Michoacán,82,Aguililla,1,Aguililla,2,Aguililla,2,Primavera-Verano,Temporal,Tonelada,Frijol,4.0,4.0,0.0,1.60,0.40,12000.00,19200.00
31833,2012,Michoacán,82,Aguililla,1,Aguililla,2,Aguililla,1,Otoño-Invierno,Riego,Tonelada,Frijol,2.5,2.5,0.0,0.90,0.36,15600.00,14040.00
34274,2011,Michoacán,82,Aguililla,1,Aguililla,2,Aguililla,2,Primavera-Verano,Temporal,Tonelada,Frijol,3.0,3.0,0.0,1.20,0.40,16000.00,19200.00
36713,2010,Michoacán,82,Aguililla,1,Aguililla,2,Aguililla,1,Otoño-Invierno,Riego,Tonelada,Frijol,3.0,3.0,0.0,0.40,0.13,15500.00,6200.00
39251,2009,Michoacán,82,Aguililla,1,Aguililla,2,Aguililla,1,Otoño-Invierno,Riego,Tonelada,Frijol,6.0,6.0,0.0,1.92,0.32,13100.00,25152.00
39258,2009,Michoacán,82,Aguililla,1,Aguililla,2,Aguililla,2,Primavera-Verano,Temporal,Tonelada,Frijol,3.0,3.0,0.0,0.75,0.25,17100.00,12825.00
44294,2007,Michoacán,82,Aguililla,1,Aguililla,2,Aguililla,1,Otoño-Invierno,Riego,Tonelada,Frijol,4.0,4.0,0.0,1.60,0.40,13000.00,20800.00
46842,2006,Michoacán,82,Aguililla,1,Aguililla,2,Aguililla,1,Otoño-Invierno,Riego,Tonelada,Frijol,6.0,6.0,0.0,1.80,0.30,9000.00,16200.00
49347,2005,Michoacán,82,Aguililla,1,Aguililla,2,Aguililla,1,Otoño-Invierno,Riego,Tonelada,Frijol,26.0,26.0,0.0,18.20,0.70,8000.00,145600.00
49355,2005,Michoacán,82,Aguililla,1,Aguililla,2,Aguililla,2,Primavera-Verano,Temporal,Tonelada,Frijol,2.0,2.0,0.0,0.70,0.35,11000.00,7700.00
51881,2004,Michoacán,82,Aguililla,1,Aguililla,2,Aguililla,1,Otoño-Invierno,Riego,Tonelada,Frijol,16.0,16.0,0.0,4.80,0.30,8500.00,40800.00
54486,2003,Michoacán,82,Aguililla,1,Aguililla,2,Aguililla,1,Otoño-Invierno,Riego,Tonelada,Frijol,21.5,21.5,0.0,7.98,0.37,6500.00,51870.00

In [95]:
df = micho_bmun.groupby('Anio')[['Sembrada','Cosechada','Siniestrada']].sum()
df['TasaExito'] = df['Cosechada'] / df['Sembrada']
df

      Sembrada  Cosechada  Siniestrada  TasaExito
Anio
2003      21.5       21.5          0.0   1.000000
2004      16.0       16.0          0.0   1.000000
2005      28.0       28.0          0.0   1.000000
2006       6.0        6.0          0.0   1.000000
2007       4.0        4.0          0.0   1.000000
2009       9.0        9.0          0.0   1.000000
2010       3.0        3.0          0.0   1.000000
2011       3.0        3.0          0.0   1.000000
2012       2.5        2.5          0.0   1.000000
2013       8.0        8.0          0.0   1.000000
2014      18.0       16.0          2.0   0.888889
2015      12.0       12.0          0.0   1.000000
2016      11.0       11.0          0.0   1.000000
2017       3.0        3.0          0.0   1.000000
2019      16.0       16.0          0.0   1.000000
2020       8.0        8.0          0.0   1.000000
2021      21.0       21.0          0.0   1.000000
2022      16.0       16.0          0.0   1.000000
2023      23.4       22.4          1.0   0.957265
2024      23.0       23.0          0.0   1.000000
2025      32.0       28.0          4.0   0.875000

In [96]:
micho_clima = climate[0]
reg_clima = micho_clima[micho_clima['Nommunicipio']==muns_0]
reg_clima.set_index('Anio',drop=True, inplace=True)
reg_clima

,Temperatura_media,Temperatura_maxima,Temperatura_minima,Precipitacion_anual,Dias_con_lluvia,Horas_precipitacion,Evapotranspiracion_anual,Idestado,Idmunicipio,Nommunicipio,Latitud,Longitud
Anio,,,,,,,,,,,,
2003,24.19,39.4,9.5,1250.6,201,1444.0,1527.14,16,2,Aguililla,18.777821,-102.752641
2004,23.78,36.6,9.8,1234.1,230,1556.0,1493.32,16,2,Aguililla,18.777821,-102.752641
2005,24.15,39.1,9.6,1147.1,191,1369.0,1549.97,16,2,Aguililla,18.777821,-102.752641
2006,23.91,36.7,10.1,1523.9,213,1634.0,1476.69,16,2,Aguililla,18.777821,-102.752641
2007,23.87,37.0,11.8,1420.0,214,1485.0,1499.78,16,2,Aguililla,18.777821,-102.752641
2008,23.81,37.6,7.5,1222.6,181,1401.0,1539.20,16,2,Aguililla,18.777821,-102.752641
2009,24.36,36.9,9.2,1030.7,200,1334.0,1547.93,16,2,Aguililla,18.777821,-102.752641
2010,23.52,37.9,10.6,1451.1,179,1657.0,1491.68,16,2,Aguililla,18.777821,-102.752641
2011,24.18,38.3,8.7,1409.4,187,1516.0,1507.65,16,2,Aguililla,18.777821,-102.752641
2012,23.73,35.2,11.7,1388.1,224,1559.0,1458.72,16,2,Aguililla,18.777821,-102.752641
2013,23.98,37.1,13.3,1431.7,221,1538.0,1488.99,16,2,Aguililla,18.777821,-102.752641
2014,23.80,36.2,12.8,1547.6,236,1840.0,1434.94,16,2,Aguililla,18.777821,-102.752641
2015,24.10,36.5,11.8,1498.2,242,1767.0,1438.86,16,2,Aguililla,18.777821,-102.752641
2016,24.17,36.9,8.2,1271.0,213,1441.0,1508.51,16,2,Aguililla,18.777821,-102.752641
2017,24.17,38.0,11.3,1178.5,183,1396.0,1508.45,16,2,Aguililla,18.777821,-102.752641
2018,23.80,36.7,10.3,1619.7,238,1881.0,1457.60,16,2,Aguililla,18.777821,-102.752641
2019,24.20,36.9,11.0,1483.0,210,1575.0,1514.66,16,2,Aguililla,18.777821,-102.752641
2020,24.50,36.9,10.6,1091.6,192,1317.0,1561.41,16,2,Aguililla,18.777821,-102.752641
2021,23.94,36.5,8.9,1688.9,186,1535.0,1528.78,16,2,Aguililla,18.777821,-102.752641
2022,24.11,37.6,11.0,1273.6,232,1891.0,1531.27,16,2,Aguililla,18.777821,-102.752641
2023,24.60,38.2,11.6,1166.4,229,1797.0,1564.54,16,2,Aguililla,18.777821,-102.752641
2024,25.14,39.2,10.6,1237.2,190,1642.0,1604.58,16,2,Aguililla,18.777821,-102.752641
2025,24.74,38.0,13.0,1359.7,228,1794.0,1534.76,16,2,Aguililla,18.777821,-102.752641

In [97]:
model = reg_clima.drop(columns=["Idestado", "Idmunicipio", "Nommunicipio","Latitud", "Longitud"])
model['TasaExito'] = df['TasaExito']
model

,Temperatura_media,Temperatura_maxima,Temperatura_minima,Precipitacion_anual,Dias_con_lluvia,Horas_precipitacion,Evapotranspiracion_anual,TasaExito
Anio,,,,,,,,
2003,24.19,39.4,9.5,1250.6,201,1444.0,1527.14,1.000000
2004,23.78,36.6,9.8,1234.1,230,1556.0,1493.32,1.000000
2005,24.15,39.1,9.6,1147.1,191,1369.0,1549.97,1.000000
2006,23.91,36.7,10.1,1523.9,213,1634.0,1476.69,1.000000
2007,23.87,37.0,11.8,1420.0,214,1485.0,1499.78,1.000000
2008,23.81,37.6,7.5,1222.6,181,1401.0,1539.20,NaN
2009,24.36,36.9,9.2,1030.7,200,1334.0,1547.93,1.000000
2010,23.52,37.9,10.6,1451.1,179,1657.0,1491.68,1.000000
2011,24.18,38.3,8.7,1409.4,187,1516.0,1507.65,1.000000
2012,23.73,35.2,11.7,1388.1,224,1559.0,1458.72,1.000000
2013,23.98,37.1,13.3,1431.7,221,1538.0,1488.99,1.000000
2014,23.80,36.2,12.8,1547.6,236,1840.0,1434.94,0.888889
2015,24.10,36.5,11.8,1498.2,242,1767.0,1438.86,1.000000
2016,24.17,36.9,8.2,1271.0,213,1441.0,1508.51,1.000000
2017,24.17,38.0,11.3,1178.5,183,1396.0,1508.45,1.000000
2018,23.80,36.7,10.3,1619.7,238,1881.0,1457.60,NaN
2019,24.20,36.9,11.0,1483.0,210,1575.0,1514.66,1.000000
2020,24.50,36.9,10.6,1091.6,192,1317.0,1561.41,1.000000
2021,23.94,36.5,8.9,1688.9,186,1535.0,1528.78,1.000000
2022,24.11,37.6,11.0,1273.6,232,1891.0,1531.27,1.000000
2023,24.60,38.2,11.6,1166.4,229,1797.0,1564.54,0.957265
2024,25.14,39.2,10.6,1237.2,190,1642.0,1604.58,1.000000
2025,24.74,38.0,13.0,1359.7,228,1794.0,1534.76,0.875000

In [91]:
import matplotlib.pyplot as plt

ideal = model[model["TasaExito"] ==1]
prob = model[model["TasaExito"] <1]
ideal

,Temperatura_media,Temperatura_maxima,Temperatura_minima,Precipitacion_anual,Dias_con_lluvia,Horas_precipitacion,Evapotranspiracion_anual,TasaExito
Anio,,,,,,,,
2003,21.01,31.6,7.5,2267.7,162,1449.0,1438.61,1.0
2004,20.97,33.0,6.6,1893.9,191,1430.0,1444.78,1.0
2005,20.80,30.5,7.6,1803.6,167,1377.0,1423.47,1.0
2006,21.13,30.3,9.7,2101.1,188,1590.0,1424.82,1.0
2007,21.09,30.3,9.6,2030.1,176,1455.0,1438.69,1.0
2008,20.49,30.8,6.8,2107.8,167,1504.0,1435.49,1.0
2009,21.03,30.1,8.4,1635.2,169,1303.0,1453.58,1.0
2010,20.30,30.4,8.3,2413.2,167,1768.0,1346.44,1.0
2012,20.95,29.6,9.7,1976.0,194,1560.0,1393.21,1.0
2013,21.03,29.7,11.0,2028.2,202,1530.0,1398.70,1.0
2014,21.21,30.1,9.5,2191.5,230,1785.0,1379.68,1.0
2015,21.74,30.5,9.1,2051.4,224,1541.0,1411.58,1.0
2016,21.25,30.6,6.3,1668.2,179,1266.0,1437.54,1.0
2017,21.08,29.9,8.6,1890.6,176,1596.0,1415.09,1.0
2018,21.35,30.8,9.5,1725.1,191,1419.0,1438.58,1.0
2019,21.22,30.1,8.2,1679.0,193,1382.0,1442.63,1.0
2020,21.35,31.5,9.0,1569.8,165,1235.0,1469.72,1.0
2021,20.90,30.5,6.6,2226.1,187,1603.0,1436.64,1.0
2022,20.81,31.1,9.2,1821.8,188,1712.0,1411.16,1.0
2023,21.59,31.0,8.9,1502.1,197,1563.0,1463.06,1.0
2024,21.46,30.5,8.0,1679.3,186,1572.0,1444.09,1.0

In [92]:
prob

,Temperatura_media,Temperatura_maxima,Temperatura_minima,Precipitacion_anual,Dias_con_lluvia,Horas_precipitacion,Evapotranspiracion_anual,TasaExito
Anio,,,,,,,,
2011,20.88,30.7,5.4,2598.1,171,1733.0,1398.86,0.916667
2025,21.62,31.6,9.8,1720.4,202,1676.0,1431.35,0.954545

In [93]:
data = reg_clima.drop(columns=["Idestado", "Idmunicipio", "Nommunicipio","Latitud", "Longitud"])
norm_data = data.copy()
for c in data.columns:
    print(data[c].min(), data[c].max())
    norm_data[c] = (data[c] - data[c].mean()) / data[c].std()

norm_data

20.3 21.74
29.6 33.0
5.4 11.0
1502.1 2598.1
162 230
1235.0 1785.0
1346.44 1469.72

,Temperatura_media,Temperatura_maxima,Temperatura_minima,Precipitacion_anual,Dias_con_lluvia,Horas_precipitacion,Evapotranspiracion_anual
Anio,,,,,,,
2003,-0.258893,1.256252,-0.655694,1.165916,-1.326452,-0.485884,0.479455
2004,-0.376224,3.128998,-1.308236,-0.157032,0.293957,-0.609189,0.698753
2005,-0.874879,-0.215191,-0.583190,-0.476621,-1.047071,-0.953145,-0.058661
2006,0.093099,-0.482727,0.939408,0.576288,0.126329,0.429169,-0.010678
2007,-0.024231,-0.482727,0.866903,0.325005,-0.544185,-0.446945,0.482298
2008,-1.784193,0.186111,-1.163227,0.600000,-1.047071,-0.128948,0.368562
2009,-0.200227,-0.750262,-0.003152,-1.072620,-0.935318,-1.433385,1.011528
2010,-2.341514,-0.348959,-0.075657,1.680868,-1.047071,1.584342,-2.796511
2011,-0.640218,0.052344,-2.178292,2.335264,-0.823566,1.357201,-0.933366
2012,-0.434889,-1.419100,0.939408,0.133535,0.461586,0.234477,-1.134182
2013,-0.200227,-1.285332,1.881969,0.318281,0.908595,0.039785,-0.939052
2014,0.327761,-0.750262,0.794399,0.896230,2.473128,1.694667,-1.615074
2015,1.882393,-0.215191,0.504380,0.400390,2.137871,0.111172,-0.481263
2016,0.445092,-0.081424,-1.525750,-0.955827,-0.376557,-1.673505,0.441424
2017,-0.053564,-1.017797,0.141857,-0.168712,-0.544185,0.468107,-0.356508
2018,0.738419,0.186111,0.794399,-0.754447,0.293957,-0.680576,0.478389
2019,0.357094,-0.750262,-0.148162,-0.917604,0.405710,-0.920696,0.622336
2020,0.738419,1.122485,0.431876,-1.304083,-1.158823,-1.874687,1.585187
2021,-0.581552,-0.215191,-1.308236,1.018686,0.070453,0.513536,0.409436
2022,-0.845547,0.587414,0.576885,-0.412208,0.126329,1.220917,-0.496191
2023,1.442403,0.453647,0.359371,-1.543686,0.629214,0.253946,1.348473
2024,1.061078,-0.215191,-0.293171,-0.916542,0.014576,0.312354,0.674229
2025,1.530401,1.256252,1.011913,-0.771081,0.908595,0.987286,0.221415