In [10]:
from yarl import URL
from scripts.config import DATA_DIR, PRELOAD_FOLDER
from zipfile import ZipFile
import geopandas as gpd

import os

purefile = DATA_DIR / "pure" / "INEGI" / "UsoSueloMexico.zip"
rawfile = DATA_DIR / "raw" / "INEGI" / "UsoSueloMexico"

if not os.path.exists(rawfile):
    with ZipFile(purefile, "r") as mfile:
        mfile.extractall(rawfile)


suelo = gpd.read_file(rawfile / "conjunto_de_datos" / "cdv_usuev250sVII_cnal.shp")
suelo.shape

(179099, 3)

In [25]:
import re
classes = suelo['DESCRIPCIO'].unique().tolist()
agro_classes = [f for f in classes if re.search(r"AGRI\.*", f)]
agro = suelo[suelo['DESCRIPCIO'].isin(agro_classes)].reset_index(drop=True)
agro['Centro'] = agro['geometry'].centroid
agro

,CLAVE,DESCRIPCIO,geometry,Centro
0,HA,AGRICULTURA DE HUMEDAD ANUAL,"POLYGON ((3088803.469 423003.312, 3088771.741 ...",POINT (3082813.216 419667.208)
1,HA,AGRICULTURA DE HUMEDAD ANUAL,"POLYGON ((3194335.928 555090.026, 3194452.732 ...",POINT (3192866.277 554191.53)
2,HA,AGRICULTURA DE HUMEDAD ANUAL,"POLYGON ((3255422.905 596486.191, 3255394.188 ...",POINT (3254526.267 595878.215)
3,HA,AGRICULTURA DE HUMEDAD ANUAL,"POLYGON ((3255270.72 594680.826, 3254799.032 5...",POINT (3254959.289 596251.987)
4,HA,AGRICULTURA DE HUMEDAD ANUAL,"POLYGON ((3254657.643 599566.929, 3254483.622 ...",POINT (3253905.762 599246.072)
...,...,...,...,...
35662,TSP,AGRICULTURA DE TEMPORAL SEMIPERMANENTE Y PERMA...,"POLYGON ((2171382.466 1061442.055, 2171487.024...",POINT (2175908.219 1051759.589)
35663,TSP,AGRICULTURA DE TEMPORAL SEMIPERMANENTE Y PERMA...,"POLYGON ((2817250.362 1065407.968, 2817171.371...",POINT (2814912.871 1060204.295)
35664,TSP,AGRICULTURA DE TEMPORAL SEMIPERMANENTE Y PERMA...,"POLYGON ((2846715.249 1067029.961, 2846635.219...",POINT (2846707.683 1067901.768)
35665,TSP,AGRICULTURA DE TEMPORAL SEMIPERMANENTE Y PERMA...,"POLYGON ((2204435.926 1078602.259, 2204473.086...",POINT (2204664.111 1072435.774)
35666,TA,AGRICULTURA DE TEMPORAL ANUAL,"POLYGON ((3446073.189 467817.338, 3446192.724 ...",POINT (3444762.466 463624.422)

In [26]:
if not os.path.exists(DATA_DIR / "raw" / "INEGI" /"Mexico"):
    with ZipFile(PRELOAD_FOLDER / "mexico_agro.zip", "r") as mfile:
        mfile.extractall(DATA_DIR / "raw" / "INEGI" /"Mexico")

mexico_map = DATA_DIR / "raw" / "INEGI" /"Mexico"
mexico = gpd.read_file(mexico_map / "Mexico" /"conjunto_de_datos" / "00ent.shp")
mexico

,CVEGEO,CVE_ENT,NOMGEO,geometry
0,01,01,Aguascalientes,"POLYGON ((2469550.852 1159302.643, 2469738.209..."
1,02,02,Baja California,"MULTIPOLYGON (((1313480.513 1831458.607, 13135..."
2,03,03,Baja California Sur,"MULTIPOLYGON (((1694656.345 1227647.637, 16946..."
3,04,04,Campeche,"MULTIPOLYGON (((3544897.199 946994.621, 354491..."
4,05,05,Coahuila de Zaragoza,"POLYGON ((2469501.165 1978862.429, 2469539.651..."
5,06,06,Colima,"MULTIPOLYGON (((1157633.318 768573.525, 115772..."
6,07,07,Chiapas,"POLYGON ((3558179.782 698365.65, 3558487.689 6..."
7,08,08,Chihuahua,"POLYGON ((1961978.327 2201082.365, 1961978.967..."
8,09,09,Ciudad de México,"POLYGON ((2802175.66 843326.718, 2801806.564 8..."
9,10,10,Durango,"POLYGON ((2107050.444 1641943.398, 2109767.527..."
10,11,11,Guanajuato,"POLYGON ((2565680.117 1091540.718, 2565824.734..."
11,12,12,Guerrero,"MULTIPOLYGON (((2723457.629 539108.73, 2723550..."
12,13,13,Hidalgo,"POLYGON ((2862652.145 1047275.093, 2862699.022..."
13,14,14,Jalisco,"MULTIPOLYGON (((2204875.697 806482.707, 220488..."
14,15,15,México,"POLYGON ((2717218.9 921748.845, 2717277.834 92..."
15,16,16,Michoacán de Ocampo,"POLYGON ((2498447.541 932170.571, 2498502.695 ..."
16,17,17,Morelos,"POLYGON ((2803716.03 789403.364, 2808717.306 7..."
17,18,18,Nayarit,"MULTIPOLYGON (((2161261.691 1008297.886, 21612..."
18,19,19,Nuevo León,"POLYGON ((2678077.258 1749532.053, 2678536.29 ..."
19,20,20,Oaxaca,"MULTIPOLYGON (((3120848.31 424036.022, 3120862..."
20,21,21,Puebla,"POLYGON ((2930796.705 987525.496, 2930806.28 9..."
21,22,22,Querétaro,"POLYGON ((2789578.589 1075590.981, 2790053.712..."
22,23,23,Quintana Roo,"MULTIPOLYGON (((4039086.131 787620.709, 403895..."
23,24,24,San Luis Potosí,"POLYGON ((2632580.368 1381778.507, 2636954.232..."
24,25,25,Sinaloa,"MULTIPOLYGON (((2050677.49 1245244.569, 205066..."
25,26,26,Sonora,"MULTIPOLYGON (((1653626.132 1730623.054, 16535..."
26,27,27,Tabasco,"POLYGON ((3503138.751 772685.828, 3503290.393 ..."
27,28,28,Tamaulipas,"POLYGON ((2723631.021 1736758.631, 2723715.07 ..."
28,29,29,Tlaxcala,"POLYGON ((2912008.539 864103.572, 2912035.825 ..."
29,30,30,Veracruz de Ignacio de la Llave,"MULTIPOLYGON (((3119599.686 810246.093, 311958..."
30,31,31,Yucatán,"MULTIPOLYGON (((3511760.832 1023282.324, 35117..."
31,32,32,Zacatecas,"POLYGON ((2470352.986 1453426.983, 2473254.843..."

In [27]:
agroent = gpd.sjoin(mexico, agro, how="inner", predicate="contains").reset_index(drop=True)
agroent.drop(columns = ['index_right', 'CLAVE', 'CVEGEO'], inplace=True)

/tmp/ipykernel_45524/1135253261.py:1: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: EPSG:6372
Right CRS: PROJCS["Albers_Conic_Equal_Area",GEOGCS["GCS_GRS_1 ...

  agroent = gpd.sjoin(mexico, agro, how="inner", predicate="contains").reset_index(drop=True)

In [28]:
agroent['Centro']=agroent['Centro'].to_crs(epsg=4326)
agroent

,CVE_ENT,NOMGEO,geometry,DESCRIPCIO,Centro
0,01,Aguascalientes,"POLYGON ((2469550.852 1159302.643, 2469738.209...",AGRICULTURA DE RIEGO ANUAL Y SEMIPERMANENTE,POINT (-102.28592 21.72969)
1,01,Aguascalientes,"POLYGON ((2469550.852 1159302.643, 2469738.209...",AGRICULTURA DE TEMPORAL ANUAL,POINT (-102.40975 21.77244)
2,01,Aguascalientes,"POLYGON ((2469550.852 1159302.643, 2469738.209...",AGRICULTURA DE TEMPORAL ANUAL,POINT (-102.5158 21.79584)
3,01,Aguascalientes,"POLYGON ((2469550.852 1159302.643, 2469738.209...",AGRICULTURA DE RIEGO ANUAL,POINT (-102.46886 21.81088)
4,01,Aguascalientes,"POLYGON ((2469550.852 1159302.643, 2469738.209...",AGRICULTURA DE TEMPORAL ANUAL,POINT (-102.5426 21.81567)
...,...,...,...,...,...
33670,32,Zacatecas,"POLYGON ((2470352.986 1453426.983, 2473254.843...",AGRICULTURA DE TEMPORAL ANUAL,POINT (-101.70467 24.75622)
33671,32,Zacatecas,"POLYGON ((2470352.986 1453426.983, 2473254.843...",AGRICULTURA DE TEMPORAL ANUAL,POINT (-101.7887 24.86394)
33672,32,Zacatecas,"POLYGON ((2470352.986 1453426.983, 2473254.843...",AGRICULTURA DE TEMPORAL ANUAL,POINT (-102.12415 24.78334)
33673,32,Zacatecas,"POLYGON ((2470352.986 1453426.983, 2473254.843...",AGRICULTURA DE TEMPORAL ANUAL,POINT (-102.13454 24.79761)
33674,32,Zacatecas,"POLYGON ((2470352.986 1453426.983, 2473254.843...",AGRICULTURA DE RIEGO ANUAL,POINT (-102.00323 24.86572)

In [30]:
agropoints = agroent['Centro'].to_list()
agrocoords = [p.coords[0] for p in agropoints]

agrocoords

[(-102.28591602335558, 21.72969343327807),
 (-102.40975006811368, 21.77243531020748),
 (-102.51579591803714, 21.795837141742023),
 (-102.4688593743015, 21.810878688139404),
 (-102.54260394243583, 21.815668400078007),
 (-102.47401208108364, 21.82111352485242),
 (-102.50706015594378, 21.824792441987075),
 (-102.5353547274295, 21.850170059294136),
 (-102.30092512226852, 21.744920018325043),
 (-102.36349321269195, 21.750914530967385),
 (-102.3405643280743, 21.766569080950305),
 (-102.32019671495242, 21.77945372415422),
 (-102.30410332172106, 21.7850455482622),
 (-102.30532013432367, 21.79488474179825),
 (-102.3366257919657, 21.799175103435783),
 (-102.26830043879052, 21.802961308395794),
 (-102.27065937253349, 21.814009134288003),
 (-102.27052003010203, 21.837922361046775),
 (-102.78681711569446, 21.823016866206785),
 (-102.12012915878556, 21.83274016112649),
 (-102.11251584526886, 21.868210991013513),
 (-102.07252865853124, 21.93334212423573),
 (-102.4542460534553, 22.162783053927793),
 (-102.55262687204059, 22.16461551703717),
 (-102.40945821224706, 22.169671421863775),
 (-102.43750283792637, 22.22466500333806),
 (-102.42844847665307, 22.2675657143315),
 (-102.44062823835019, 22.37299599851229),
 (-102.17524973927259, 22.290773022651244),
 (-102.25312151148685, 22.348676012347937),
 (-102.2471801168922, 22.380486772989606),
 (-102.23659295370452, 22.387809243953),
 (-102.26765444048071, 22.39692647178043),
 (-102.34065881618207, 22.402638173089343),
 (-102.12517893191904, 21.990946727936556),
 (-101.98598018613872, 22.027712004214862),
 (-102.06203097348613, 22.04853243949508),
 (-102.07811700479934, 22.055628728016917),
 (-101.96163145158982, 22.06091340425009),
 (-101.99229325179549, 22.071666160108308),
 (-102.12464468052222, 22.077387008833174),
 (-102.11534150933082, 22.085096412544715),
 (-101.89793911255794, 22.052731663714052),
 (-102.81702585222436, 21.831280376792545),
 (-102.7954501165226, 21.850680963574337),
 (-102.64274284910017, 21.85299820762328),
 (-102.8129654810233, 21.871326399775118),
 (-102.73274446856874, 21.87734490861597),
 (-102.54336821306191, 21.854889224549307),
 (-102.62364380075005, 21.85906442614009),
 (-102.38642925918772, 21.861058226966424),
 (-102.38829441880002, 21.863206571105408),
 (-102.49666705413959, 21.867779188758554),
 (-102.47096218745881, 21.879240876850034),
 (-102.62204786905903, 21.88025818962806),
 (-102.41080034906699, 21.896312655925257),
 (-102.57189194600953, 21.899888404901567),
 (-102.56240548530826, 21.912215665609963),
 (-102.64307806875847, 21.89757963469376),
 (-102.7030390462471, 21.902053413457903),
 (-102.79546524859948, 21.89965230155846),
 (-102.73582999374399, 21.90511226487504),
 (-102.73052704496392, 21.918425475861092),
 (-102.71550859680049, 21.92621881512427),
 (-102.74186151919113, 21.938686882863667),
 (-102.73460960564955, 21.94682641053295),
 (-102.70670090103185, 21.965304457387923),
 (-102.66858856206086, 22.001022993545636),
 (-102.72301740869625, 22.007211000598225),
 (-102.67805582662521, 22.02763569831464),
 (-102.53530233886714, 21.92017630035707),
 (-102.48915063852041, 21.928689833261917),
 (-102.44699893744374, 21.930944877745652),
 (-102.46062011019356, 21.932310887646267),
 (-102.5590176589086, 21.936462803767622),
 (-102.45445369510222, 21.945324807997828),
 (-102.59672161070321, 21.95592473694612),
 (-102.50755533540963, 22.075649218850927),
 (-102.52017226543448, 22.08770951449911),
 (-102.48140038942631, 22.12669291705124),
 (-102.15539486539694, 21.9875414731957),
 (-102.20070499381758, 21.98882001273381),
 (-102.36395134040626, 21.988990195798337),
 (-102.21775531088609, 22.02085202928066),
 (-102.34419328210622, 22.05081116878199),
 (-102.22137980309444, 22.059330808668374),
 (-102.27112001111428, 22.06348663942387),
 (-102.31092074101662, 22.074328918165676),
 (-102.32779164177163, 22.101304929541566),
 (-102.16824659573902, 22.119409260922914),
 (-102.19329580139916, 22.13903947545394),
 (-102.16484602155805, 22.139774255291268),
 (-102.36056966177968, 22.14171860444934),
 (-102.19895968887319, 22.14378899396668),
 (-102.3314705260554, 22.19799892397253),
 (-102.36121879765575, 22.266229116691218),
 (-102.34342691679969, 22.262899156690636),
 (-102.21455969454708, 22.274893322629175),
 (-102.20888692710398, 22.288334180998344),
 (-102.09803545500823, 22.090465123598385),
 (-102.01366129477346, 22.098159718513898),
 (-101.96053338053858, 22.10171770892229),
 (-101.93637608577868, 22.113456041272368),
 (-101.97805116061011, 22.118333902760515),
 (-102.10748871062675, 22.15068793210632),
 (-102.12717254091199, 22.157255001483914),
 (-102.11637188017616, 22.17703913210383),
 (-102.06114856018417, 22.245396457273078),
 (-102.07742904084834, 22.261124041934995),
 (-113.88763333510289, 28.26631384906307),
 (-113.9449132175594, 28.26773223945402),
 (-113.97545983170166, 28.2846248336735),
 (-114.02054119872868, 28.300759018582596),
 (-115.24003669082994, 29.59149946308498),
 (-115.48944238721324, 29.791584375385835),
 (-115.51779950058652, 29.839011444503488),
 (-115.66121423223092, 29.825668829130866),
 (-115.64044547587125, 29.832795164318348),
 (-115.44107383035553, 29.849815657997993),
 (-115.5090633803636, 29.85959074327272),
 (-115.54390855761365, 29.869957995438313),
 (-115.53228367706903, 29.871420264468334),
 (-115.50684728279114, 29.88148940901205),
 (-115.51372131964702, 29.896076203272262),
 (-115.01220451479632, 29.952624880455296),
 (-114.99557785145234, 29.953945297316288),
 (-115.56137559047471, 29.899907990595782),
 (-115.49580092320801, 29.917000048356485),
 (-115.53653305856912, 29.91338713790368),
 (-115.06901117978045, 29.959372256824775),
 (-115.10965912440868, 29.96094467713125),
 (-115.0740394265277, 29.965092349369733),
 (-115.2108369671546, 29.969480318767275),
 (-115.66310924253173, 30.002327957092497),
 (-115.32381543196813, 30.052947755458312),
 (-115.70935878286924, 30.026314461128536),
 (-115.75432099619495, 30.042726010293094),
 (-115.77073014181143, 30.054524327839733),
 (-115.68287547534382, 30.07114343999234),
 (-115.71405972095727, 30.064351737393032),
 (-115.69674066460422, 30.078883910110097),
 (-115.63013502966616, 30.087747205578157),
 (-115.68143219846436, 30.09180280216784),
 (-115.74414822379407, 30.08721685564398),
 (-115.63666481616617, 30.10604626499564),
 (-115.66119373831808, 30.10621706018742),
 (-115.63281753771363, 30.116798632466672),
 (-115.61515801385968, 30.128056262269972),
 (-115.56324873951502, 30.13668860296627),
 (-115.62089635398577, 30.133619226932442),
 (-115.58549564441199, 30.148367180753418),
 (-115.59935744025104, 30.15221711817487),
 (-115.5697400840643, 30.15657336314974),
 (-115.45579212186416, 30.20290649917097),
 (-115.7939639021194, 30.272725270569747),
 (-115.81254382583138, 30.317886702206536),
 (-115.7735132844632, 30.332629696719245),
 (-115.82103293215013, 30.332489943632442),
 (-115.81855394174973, 30.36873304953377),
 (-115.84714272263436, 30.37286043519141),
 (-115.78555580066077, 30.378991325947677),
 (-115.82723760321463, 30.382155481992918),
 (-115.79422779313711, 30.398003140265537),
 (-115.8671863807373, 30.40636253375941),
 (-115.80217309991485, 30.407395768361226),
 (-115.78084599603544, 30.424499683960377),
 (-115.7923618125624, 30.441782055388067),
 (-115.83491051552753, 30.43987904951423),
 (-115.90836416388859, 30.43437699452348),
 (-115.83500565595949, 30.441735917011417),
 (-115.81074994695969, 30.44635281532524),
 (-115.80483892552016, 30.46708147042364),
 (-116.019221280363, 30.4999635088308),
 (-115.83190223734839, 30.51871923602812),
 (-115.86126136101457, 30.520221091219664),
 (-115.81704423202659, 30.55203824491685),
 (-115.88914028411264, 30.55583401033316),
 (-115.87795683983997, 30.572845130834676),
 (-115.8753243633239, 30.576555316712145),
 (-115.86610025324082, 30.586558213710294),
 (-115.93800792346987, 30.572728404214516),
 (-115.12403392470844, 30.660258405349396),
 (-115.91405549836372, 30.60943205199352),
 (-115.1068058534781, 30.670627291126937),
 (-115.92842365564556, 30.640209755626362),
 (-115.94239448059015, 30.65551560728968),
 (-115.94789836105751, 30.670063723594),
 (-115.93615772939877, 30.678586221615785),
 (-115.16298935809891, 30.801966207252086),
 (-115.97844243715092, 30.7369587699251),
 (-115.96318761803032, 30.755863786433082),
 (-116.0343109694175, 30.754053457590764),
 (-115.97575845779038, 30.759505015088664),
 (-115.9922679262455, 30.760268982561282),
 (-115.93694872756603, 30.769168450809058),
 (-116.05115598163701, 30.789154416256657),
 (-115.99354050718108, 30.79561792278479),
 (-116.02960704862777, 30.8088392062792),
 (-116.00417634308194, 30.811962398899812),
 (-116.06382661233725, 30.812248091946426),
 (-116.004229079672, 30.854771932789802),
 (-115.92679873406868, 30.866927573062476),
 (-116.04806918890796, 30.871401282051202),
 (-115.88867636338585, 30.88690259439748),
 (-116.15169833173447, 30.886546831447514),
 (-116.17249884185502, 30.88887861330558),
 (-116.112287479643, 30.897244856857636),
 (-116.04996253531644, 30.904257237577358),
 (-116.11396793415074, 30.902742933036542),
 (-116.10717783198683, 30.910558409328377),
 (-116.12255219781629, 30.913975720126935),
 (-115.9418428873172, 30.939397232831677),
 (-115.90086985081733, 30.95129285659402),
 (-115.73738437267107, 30.974754942361905),
 (-116.20479964985469, 30.93729090510241),
 (-116.21000054396589, 30.93657114630149),
 (-116.15299286786939, 30.94004314277419),
 (-116.24084247040551, 30.935439826334456),
 (-115.97370895755577, 30.955430426993797),
 (-115.74840432455831, 30.97791849251912),
 (-116.03146878944831, 30.956581837693392),
 (-115.77760516095263, 30.98177870987478),
 (-115.89036084475671, 30.974316860676538),
 (-115.9977547856955, 30.962501062063765),
 (-116.17445830605722, 30.948054120738885),
 (-115.92321050509939, 30.9710797522812),
 (-116.22427121530136, 30.94910871982861),
 (-116.1472299103027, 30.961027839092566),
 (-115.97008564849375, 30.976289896395148),
 (-116.07528184865944, 30.96897480745039),
 (-116.09301181586983, 30.970250165643375),
 (-116.1380658917695, 30.97006356245006),
 (-116.09199849517684, 30.976840443520494),
 (-116.16890642274052, 30.97188567637025),
 (-116.07932418806396, 30.978949326983724),
 (-116.05783912760567, 30.983571356378512),
 (-116.1449388095731, 30.978798875324188),
 (-115.90578864416688, 31.000208653191713),
 (-116.00261153579271, 30.99407235712753),
 (-116.10757044770354, 30.986962082907702),
 (-116.14968866997903, 30.98484647619877),
 (-116.0412315902083, 30.995466002812574),
 (-116.004455686955, 30.999176468830704),
 (-116.03597162432668, 30.99649117427617),
 (-116.20308179708549, 30.986039129791056),
 (-116.00704853150472, 31.01026077848576),
 (-115.99325531446827, 31.013105723564394),
 (-116.21632425883159, 30.999114141444355),
 (-116.03022143793113, 31.01500467591972),
 (-116.24196471217067, 31.011329780884754),
 (-116.04687211552053, 31.0358944393843),
 (-116.06191701890631, 31.048355398687985),
 (-116.16765318088693, 31.041305291950763),
 (-116.06473999939178, 31.052320261643164),
 (-116.20793843154304, 31.043661318483252),
 (-116.10773470519143, 31.065132511465666),
 (-116.16575111933507, 31.059747968433356),
 (-116.1757263500552, 31.062720457620586),
 (-116.0702913370909, 31.07056448732383),
 (-116.1205445784827, 31.073242360534035),
 (-116.19632443379841, 31.067972623753086),
 (-116.10813618660825, 31.083276256398257),
 (-116.19428609435013, 31.080700083919),
 (-116.0885465504671, 31.100675880731835),
 (-116.16833474148902, 31.11224994779997),
 (-116.10831653686655, 31.117279404605615),
 (-116.11857921766877, 31.11761101449179),
 (-116.14771538916628, 31.116992433795946),
 (-116.13857190541331, 31.127317704452018),
 (-116.07436409128498, 31.136029397435866),
 (-116.12723006344702, 31.135236663942788),
 (-116.08127779348999, 31.146604700988842),
 (-116.25864664859643, 31.131943815394628),
 (-116.08376793499707, 31.1477448051212),
 (-116.0847021148924, 31.157394987313786),
 (-116.18300862881892, 31.149891611987215),
 (-116.13288402066041, 31.156081215249536),
 (-116.17564120081882, 31.15215688764699),
 (-116.17035244093354, 31.15655960737158),
 (-116.14548772784052, 31.168648748007218),
 (-116.19421160621904, 31.174599721576364),
 (-116.1588000529418, 31.194929423346622),
 (-116.13362827251817, 31.20903832926333),
 (-116.16032871296767, 31.22732872342758),
 (-116.13424269972377, 31.234400605420497),
 (-116.12190471070191, 31.23979622907443),
 (-116.10791532178018, 31.251367055593647),
 (-116.05001257117898, 31.27127056154475),
 (-116.12891086951929, 31.263190434205477),
 (-116.12854373220627, 31.273972165751395),
 (-116.20645346005138, 31.26969292532033),
 (-116.11761695348159, 31.271674096941886),
 (-116.33598435419388, 31.254057150449956),
 (-116.34365935016962, 31.266890468272976),
 (-116.35235525804427, 31.26700874447565),
 (-115.58822136583193, 31.339437859911687),
 (-116.3425716647993, 31.276609623045818),
 (-116.28245154713605, 31.286452257090364),
 (-116.06987587007782, 31.302912686447264),
 (-116.36681275586673, 31.278879230580173),
 (-116.28232955146304, 31.288069555973138),
 (-116.0727016147302, 31.30951009623511),
 (-115.61818281648594, 31.35280443730194),
 (-116.3657697857978, 31.293089895856088),
 (-116.39871445910016, 31.29594252818787),
 (-116.08367350643103, 31.324978377879113),
 (-115.72644842108433, 31.36151499408395),
 (-115.64038926658385, 31.36815709515059),
 (-116.03268605170555, 31.340139328549224),
 (-116.08045713215378, 31.33554775056285),
 (-116.20816516153695, 31.327934018817952),
 (-116.2759224519386, 31.334554927935283),
 (-116.2638738402018, 31.332139142154567),
 (-116.20394154296545, 31.35088873361665),
 (-116.20731417920437, 31.35501164721101),
 (-116.10549740383084, 31.365640881324712),
 (-116.13667619465856, 31.36841418649983),
 (-116.18973282588775, 31.363912383790083),
 (-116.29802522156886, 31.360707933194238),
 (-116.37948133540674, 31.358381469495676),
 (-116.1533106220212, 31.39109449503361),
 (-116.3246198010875, 31.382843415024087),
 (-116.36663832227487, 31.39592530987758),
 (-116.32709538580775, 31.402624166322617),
 (-116.26301624320678, 31.421680718964616),
 (-116.42530518228763, 31.425347044981926),
 (-116.41982506586488, 31.42114310498999),
 (-116.40044476933815, 31.431099589941724),
 (-116.47896876343172, 31.4276219663911),
 (-116.26264340320908, 31.454384857901076),
 (-116.47895458593966, 31.437410920998026),
 (-116.48874585683299, 31.43594185079868),
 (-116.38271103019251, 31.44516022574812),
 (-116.50467661265844, 31.43550822002026),
 (-116.1595337662041, 31.47007659152553),
 (-116.16302573095027, 31.46644516917715),
 (-116.26483061966577, 31.462190375857702),
 (-116.53271888682339, 31.444503135679202),
 (-116.29572000084049, 31.465942520536384),
 (-116.37292454517531, 31.468525163133993),
 (-116.55337776308758, 31.456599774731902),
 (-116.26531778359654, 31.48385055047416),
 (-116.56812068053392, 31.466039678832217),
 (-116.51651401317898, 31.471007238625518),
 (-116.56988916234342, 31.47389737816256),
 (-115.80179144330233, 31.548338146869234),
 (-116.4337607143371, 31.49622429353897),
 (-115.78245755300675, 31.55656979521661),
 (-116.4689405725486, 31.500031948422425),
 (-116.30715251520706, 31.51715952703031),
 (-116.4017435906411, 31.515192773344886),
 (-116.33102196103603, 31.52702624260852),
 (-116.34519830690341, 31.526767488639855),
 (-116.28127009897517, 31.534684657324746),
 (-116.32545533915807, 31.531583402099027),
 (-116.40247898654161, 31.5268787521145),
 (-116.56416534649604, 31.52284364342749),
 (-115.8631412725048, 31.579544629107613),
 (-116.4051245816741, 31.537370301477047),
 (-115.82479529681179, 31.59664978538426),
 (-116.38419429328643, 31.54981922890662),
 (-115.85565842998861, 31.59962308388686),
 (-116.49814431776423, 31.553081223298687),
 (-116.42749428845471, 31.56801146313152),
 (-116.61666158229173, 31.549830272092322),
 (-116.5690950461344, 31.566298425525904),
 (-116.59119611159706, 31.576528672913778),
 (-115.90106037549533, 31.642275125192896),
 (-115.96585892258067, 31.636279299599774),
 (-115.89412622519009, 31.646368404387857),
 (-116.43244787728514, 31.6305465436171),
 (-116.44405529375973, 31.632938843422416),
 (-116.44438838290658, 31.643280843250032),
 (-116.44495969876918, 31.649782771532415),
 (-116.17796728415107, 31.69097999439902),
 (-115.94340910348798, 31.740103168925998),
 (-116.07107479807786, 31.732421393246483),
 (-116.6570555695227, 31.694399389367227),
 (-116.44699514474509, 31.71188739135309),
 (-115.3556537535107, 31.812312299814263),
 (-116.54615161678652, 31.721713679457014),
 (-116.54987176166773, 31.723780237217355),
 (-116.55720280980627, 31.723481526237528),
 (-116.57650108954773, 31.782885469443098),
 (-116.04896197002215, 31.83274638405496),
 (-116.58132692755402, 31.78716032694221),
 (-116.07047402700583, 31.834245306617408),
 (-116.19479255184534, 31.833915955191262),
 (-116.16389937817775, 31.843083631663447),
 (-116.48117627242601, 31.827491147362192),
 (-116.20310464989066, 31.85265948347016),
 (-116.47524089029363, 31.834187295503472),
 (-116.18907889138718, 31.862618829936952),
 (-116.22057332754667, 31.86688966024042),
 (-116.12857707582862, 31.879088085115487),
 (-116.54918177740038, 31.84747457173968),
 (-116.15129275731864, 31.881928045395966),
 (-116.23601800411444, 31.876371018007298),
 (-116.24789004485869, 31.88738042826917),
 (-116.20377764591805, 31.88791448768374),
 (-116.08301129519882, 31.902405319776268),
 (-115.01183045928633, 31.996060080088295),
 (-116.44910524113274, 31.89958192168612),
 (-115.01422030701085, 32.019651662712036),
 (-116.13502959952093, 31.932554392554607),
 (-116.49795991565757, 31.901469045329648),
 (-116.36523589156828, 31.91680980519743),
 (-116.52989286405695, 31.907921233959907),
 (-116.54025458591093, 31.91432796734929),
 (-116.591763307384, 31.911348445179396),
 (-116.27775726313506, 31.942430017109434),
 (-116.69835721860811, 31.90389752211289),
 (-116.46887631836184, 31.92709362171757),
 (-116.58378047054156, 31.919003235083455),
 (-116.50655641519192, 31.924178654754666),
 (-116.51115815658072, 31.931764169096386),
 (-116.68162650933265, 31.91689669937106),
 (-116.53035652328151, 31.933062238146302),
 (-116.71464766062329, 31.918928071498282),
 (-115.00758685517248, 32.05903874421937),
 (-115.04865864620564, 32.07565241356809),
 (-116.73160589978141, 31.94018638377019),
 (-115.06926501539239, 32.08224719000545),
 (-116.65741431615736, 31.96527072024671),
 (-115.0763757343566, 32.10244444659673),
 (-116.66597539367662, 31.972356414578503),
 (-115.0339242654563, 32.10826767051215),
 (-116.67708333108247, 31.97701322396514),
 (-115.10528151835643, 32.120064193156374),
 (-116.65762675267831, 31.9930056293489),
 (-115.06400614654422, 32.12807319386614),
 (-116.75061973069037, 31.985122249123236),
 (-116.67075710352661, 32.00022522441554),
 (-115.00476940896984, 32.13576852484911),
 (-115.07642166915622, 32.13405262555631),
 (-116.76182919389295, 32.00281398686561),
 (-116.0772847376018, 32.06370661251682),
 (-116.6490277728976, 32.017368728955134),
 (-115.09526440216902, 32.15579662025016),
 (-116.61450872700418, 32.031172051183944),
 (-116.7578391675197, 32.023015542118266),
 (-115.17647302052349, 32.158588564798464),
 (-116.77365527573761, 32.02553705944185),
 (-116.55345774638525, 32.050336039415974),
 (-116.84474550986673, 32.02641863548874),
 (-116.62022967270649, 32.04901589895291),
 (-116.65151523210679, 32.050491615916044),
 (-116.59438438006545, 32.05986882604138),
 (-115.28206241887479, 32.17183632442175),
 (-116.73776719394465, 32.05261585364414),
 (-116.78671806176686, 32.054352245275645),
 (-115.67456870017286, 32.15929472455734),
 (-116.63990701077685, 32.07951266101244),
 (-116.6056502054321, 32.08500298368798),
 (-116.82777142288874, 32.065798189817436),
 (-116.56354181104318, 32.08976833118268),
 (-115.17057466383723, 32.21665958701684),
 (-116.49083113868441, 32.116336943926086),
 (-116.53438147084519, 32.11279079810786),
 (-116.78495868527557, 32.087670201982725),

In [34]:
agroent.geometry = agroent['Centro']

In [36]:
# Tu lista de datos


# Abrir (o crear) el archivo en modo escritura ('w')
with open("agrocoords.txt", "w", encoding="utf-8") as archivo:
    for elemento in agrocoords:
        archivo.write(f"{elemento}\n")